CREATE TABLE [dbo].[TestRuns] (
    [id]                   INT           IDENTITY (1, 1) NOT NULL,
    [ExternalTestId]       INT           NULL,
    [TestPassSessionId]    INT           NOT NULL,
    [TestName]             VARCHAR (50)  NOT NULL,
    [TestPassTypeId]       INT           NOT NULL,
    [BuildId]              INT           NOT NULL,
    [BuildConfigurationId] INT           NULL,
    [SourceChangelist]     INT           NULL,
    [CategoryId]           INT           NULL,
    [TestRunStateId]       INT           NOT NULL,
    [RequestStart]         DATETIME      NULL,
    [RequestEnd]           DATETIME      NULL,
    [RunStart]             DATETIME      NULL,
    [RunEnd]               DATETIME      NULL,
    [HostMachineId]        INT           NOT NULL,
    [HostMachineStateId]   INT           NOT NULL,
    [PriorityId]           INT           NULL,
    [Succeeded]            BIT           NOT NULL,
    [Cancelled]            BIT           NOT NULL,
    [FailureId]            INT           NULL,
    [OutputPath]           VARCHAR (250) NULL,
    CONSTRAINT [PK_TestRuns] PRIMARY KEY CLUSTERED ([id] ASC) WITH (FILLFACTOR = 40),
    CONSTRAINT [FK_TestRuns_BuildConfigurations] FOREIGN KEY ([BuildConfigurationId]) REFERENCES [dbo].[BuildConfigurations] ([id]),
    CONSTRAINT [FK_TestRuns_Builds] FOREIGN KEY ([BuildId]) REFERENCES [dbo].[Builds] ([id]),
    CONSTRAINT [FK_TestRuns_HostMachines] FOREIGN KEY ([HostMachineId]) REFERENCES [dbo].[HostMachines] ([id]),
    CONSTRAINT [FK_TestRuns_HostMachineStates] FOREIGN KEY ([HostMachineStateId]) REFERENCES [dbo].[HostMachineStates] ([id]),
    CONSTRAINT [FK_TestRuns_Priorities] FOREIGN KEY ([PriorityId]) REFERENCES [dbo].[TestRunPriorities] ([id]),
    CONSTRAINT [FK_TestRuns_TestCategories] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[TestRunCategories] ([id]),
    CONSTRAINT [FK_TestRuns_TestFailures] FOREIGN KEY ([FailureId]) REFERENCES [dbo].[TestRunFailures] ([id]),
    CONSTRAINT [FK_TestRuns_TestPassSessions] FOREIGN KEY ([TestPassSessionId]) REFERENCES [dbo].[TestPassSessions] ([id]),
    CONSTRAINT [FK_TestRuns_TestPassTypes] FOREIGN KEY ([TestPassTypeId]) REFERENCES [dbo].[TestPassTypes] ([id]),
    CONSTRAINT [FK_TestRuns_TestRunStates] FOREIGN KEY ([TestRunStateId]) REFERENCES [dbo].[TestRunStates] ([id])
);

