CREATE TABLE [dbo].[TestRunBugs] (
    [id]                 INT           IDENTITY (1, 1) NOT NULL,
    [Title]              VARCHAR (255) NOT NULL,
    [ExternalId]         INT           NOT NULL,
    [TestRunsDevkitsId]  INT           NOT NULL,
    [BugDatabaseProject] VARCHAR (50)  NOT NULL,
    [AutoGenerated]      BIT           NULL,
    CONSTRAINT [PK_TestRunBugs] PRIMARY KEY CLUSTERED ([id] ASC) WITH (FILLFACTOR = 40),
    CONSTRAINT [FK_TestRunBugs_TestRunsDevkits] FOREIGN KEY ([TestRunsDevkitsId]) REFERENCES [dbo].[TestRunsDevkits] ([id]),
    CONSTRAINT [UX_TestRunBugs] UNIQUE NONCLUSTERED ([ExternalId] ASC, [TestRunsDevkitsId] ASC, [BugDatabaseProject] ASC) WITH (FILLFACTOR = 40)
);

